services:
  nginx:
    container_name: nginx
    image: arm64v8/nginx:latest
    ports:
      - '80:80'
    depends_on:
      - php
    volumes:
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./${CONVERT_PROJECT_NAME}:/var/www/html/${CONVERT_PROJECT_NAME}
      - ./docker/nginx/logs:/var/log/nginx
      - ./docker/profiler/:/var/profiler
      - ~/.ssh:/root/.ssh:ro
    networks:
      - internal
  php:
    container_name: php
    build: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./${CONVERT_PROJECT_NAME}:/var/www/html/${CONVERT_PROJECT_NAME}
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./docker/profiler/:/var/profiler
      - ~/.ssh:/root/.ssh:ro
    env_file:
      - .env
    networks:
      - internal
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./${CONVERT_PROJECT_NAME}:/var/www/html/${CONVERT_PROJECT_NAME}
      - ./docker/mysql/data:/var/lib/mysql/
      - ./docker/mysql/config/conf.cnf:/etc/mysql/conf.d/conf.cnf
    env_file:
      - .env
    networks:
      - internal
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - internal
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - '5672:5672'
    networks:
      - internal
  node_js:
    build: ./docker/node_js
    volumes:
      - ./${CONVERT_PROJECT_NAME}:/var/www/html/${CONVERT_PROJECT_NAME}
    networks:
      - internal
networks:
  internal:
    driver: bridge